/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../LIB/STD_Types.h"
#include "../LIB/Bit_Math.h"
#include "../MCAL/RCC_Driver/RCC_Interface.h"
#include "../MCAL/GPIO_Driver/GPIO_Interface.h"
#include "../MCAL/SYSTICK_Driver/SYSTICK_Interface.h"
#include "../MCAL/LCD_Driver/LCD_Interface.h"

int main(void)
{

RCC_Init();
RCC_Enable_peripheral(RCC_AHB1ENR_GPIOA_EN);
RCC_Enable_peripheral(RCC_AHB1ENR_GPIOB_EN);
LCD_Init();
LCD_Write_Command(lcd_Clear);

//LCD_Write_Data(ASCII_M);
//LCD_Write_Data(ASCII_U);
//LCD_Write_Data(ASCII_S);
//LCD_Write_Data(ASCII_T);
//LCD_Write_Data(ASCII_A);
//LCD_Write_Data(ASCII_F);
//LCD_Write_Data(ASCII_A);

LCD_Write_String("mustafa", 8);
	while(1){
//		LCD_Write_Data(40);

	}
}


