/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include "../MCAL/RCC_Driver/RCC_Registers.h"
#include "../MCAL/RCC_Driver/RCC_Interface.h"
#include "../LIB/STD_Types.h"
#include "../LIB/Bit_Math.h"
#include "../MCAL/GPIO_Driver/GPIO_Interface.h"
#include "../MCAL/GPIO_Driver/GPIO_Register.h"

int main(void)
{
	GPIO_Pin_Cofig Led ;
	Led.port = GPIO_PORT_A ;
	Led.pin = GPIO_PIN_0 ;
	Led.Direction = GPIO_PIN_OUTPUT ;
	Led.mode = GPIO_OUTPUT_PushPull ;
	Led.Speed = GPIO_Speed_Medium ;

	GPIO_Pin_Cofig Button ;
	Button.port = GPIO_PORT_A ;
	Button.pin = GPIO_PIN_1 ;
	Button.Direction = GPIO_PIN_INPUT ;
	Button.mode = GPIO_PULLUP ;
	Button.Speed = GPIO_Speed_Medium ;

	RCC_Init();
	RCC_Enable_peripheral(RCC_AHB1ENR_GPIOA_EN);
	RCC_Enable_peripheral(RCC_AHB1ENR_GPIOB_EN);
	GPIO_PinConfig(&Led);
	GPIO_PinConfig(&Button);
	GPIO_SetPinValue(GPIO_PORT_A, GPIO_PIN_0, GPIO_Pin_High);

    while(1){
    	if(GPIO_GetPinValue(GPIO_PORT_A, GPIO_PIN_1)){
    		GPIO_SetPinValue(GPIO_PORT_A, GPIO_PIN_0, GPIO_Pin_High);
    	}else{
    		GPIO_SetPinValue(GPIO_PORT_A, GPIO_PIN_0, GPIO_Pin_LOW);
    	}
    }
}
