/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include "../MCAL/RCC_Driver/RCC_Registers.h"
#include "../MCAL/RCC_Driver/RCC_Interface.h"
#include "../LIB/STD_Types.h"
#include "../LIB/Bit_Math.h"
int main(void)
{
	RCC_Init();
	RCC_Enable_peripheral(AHP1,RCC_AHB1ENR_GPIOA_EN);

	RCC_Enable_peripheral(APB1,RCC_APB1ENR_TIM2EN);

	RCC_Enable_peripheral(APB2,RCC_APB2ENR_TIM9EN);

	RCC_Disable_peripheral(AHP1,RCC_AHB1ENR_GPIOA_EN);

	RCC_Disable_peripheral(APB1,RCC_APB1ENR_TIM2EN);

	RCC_Disable_peripheral(APB2,RCC_APB2ENR_TIM9EN);

    while(1){

    }
}
